service: scrap-crawler

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512
  timeout: 30
  # ap-northeast-2 === 서울
  region: ap-northeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: "*"

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**

functions:
  scrap:
    handler: src/index.handler
    events:
      - http:
          path: /scrap
          method: get
      # - schedule: cron(5 0-8 ? * MON-FRI *)
