service: tech-scrap

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  timeout: 30
  # ap-northeast-2 === 서울
  region: ap-northeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: "*"

functions:
  crawl:
    handler: src/crawl.handler
    events:
      - schedule: rate(1 hour)
