module.exports.blogs = [
  { id: 1, name: "kakao", rss: "https://tech.kakao.com/feed/" },
  { id: 2, name: "woowa", rss: "https://techblog.woowahan.com/feed/" },
  { id: 3, name: "banksalad", rss: "https://blog.banksalad.com/rss.xml" },
  { id: 4, name: "kurly", rss: "https://helloworld.kurly.com/feed.xml" },
  { id: 5, name: "watcha", rss: "https://medium.com/feed/watcha" },
  { id: 6, name: "daangn", rss: "https://medium.com/feed/daangn" },
  { id: 7, name: "wanted", rss: " https://medium.com/feed/wantedjobs" },
  { id: 8, name: "line", rss: " https://engineering.linecorp.com/ko/feed/" },
  {
    id: 9,
    name: "ridi",
    rss: " https://www.ridicorp.com/story-category/tech-blog/feed/",
  },
  { id: 11, name: "toss", rss: "https://toss.tech/rss.xml" },
  { id: 12, name: "zigbang", rss: "https://medium.com/feed/zigbang" },
  { id: 13, name: "yanolja", rss: "https://yanolja.github.io/feed.xml" },
  { id: 14, name: "musinsa", rss: "https://medium.com/feed/musinsa-tech" },
  {
    id: 15,
    name: "kakaoenterprise",
    rss: "https://tech.kakaoenterprise.com/rss",
  },
  { id: 16, name: "11st", rss: "https://11st-tech.github.io/rss/" },
  { id: 17, name: "brandi", rss: "http://labs.brandi.co.kr/feed" },
  { id: 18, name: "idus", rss: "https://medium.com/feed/idus-tech" },
  { id: 19, name: "bbros", rss: "https://boostbrothers.github.io/feed" },
  {
    id: 20,
    name: "kakaoent",
    rss: "https://fe-developers.kakaoent.com/rss.xml",
  },
  { id: 22, name: "class101", rss: "https://medium.com/feed/class101" },
  { id: 23, name: "spoon", rss: "https://medium.com/feed/spoontech" },
  { id: 24, name: "soomgo", rss: "https://medium.com/feed/soomgo-tech" },
  { id: 25, name: "remember", rss: "https://blog.dramancompany.com/feed/" },
  {
    id: 26,
    name: "liner",
    rss: "https://blog.getliner.com/category/blogpost/tech/feed/",
  },
  { id: 27, name: "athenaslab", rss: "https://medium.com/feed/athenaslab" },
  { id: 28, name: "ssg", rss: "https://medium.com/feed/ssgtech" },
  { id: 29, name: "zum", rss: "https://zuminternet.github.io/feed" },
  { id: 30, name: "petfriends", rss: "https://pfdev.medium.com/feed" },
  { id: 31, name: "opgg", rss: " https://log.op.gg/feed/" },
  { id: 32, name: "kimjeonghwan", rss: "https://jeonghwan-kim.github.io/feed" },
  { id: 33, name: "toast", rss: "https://ui.toast.com/rss" },
  { id: 34, name: "jojoldu", rss: "https://jojoldu.tistory.com/rss" },
  { id: 35, name: "yogiyo", rss: "https://techblog.yogiyo.co.kr/feed" },
  { id: 36, name: "hyperconnect", rss: "https://hyperconnect.github.io/feed" },
  { id: 37, name: "29cm", rss: "https://medium.com/feed/29cm" },
];
